name: Labjack T4 Test Fixture

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest test_labjack_t4_fixture.py